(ns resolver-sim.forensic.evidence-pack
  "Portable evidence pack: bundles artifacts from a run directory into a
   publishable, independently reproducible archive.
   Used by bb evidence:pack and bb evidence:verify."
  (:require [clojure.java.io :as io]
            [clojure.data.json :as json]
            [clojure.string :as str]
            [clojure.java.shell :as shell])
  (:import [java.security MessageDigest]))

(defn- sha256-file [path]
  (let [f (java.io.File. path)]
    (when (.isFile f)
      (let [d (MessageDigest/getInstance "SHA-256")]
        (.update d (java.nio.file.Files/readAllBytes (.toPath f)))
        (apply str (map #(format "%02x" (bit-and % 0xff)) (.digest d)))))))

(def pack-manifest-fields
  "Files to copy from a run directory into the evidence pack.
   Each entry: [source-filename, target-filename]"
  [["pre-run-commitment.json" "pre-run-commitment.json"]
   ["pre-run-commitment.sig.json" "signatures/pre-run-commitment.sig.json"]
   ["execution-dag.json" "execution-dag.json"]
   ["execution-dag.sig.json" "signatures/execution-dag.sig.json"]
   ["chain-cursor-final.json" "evidence/chain-cursor-final.json"]
   ["evidence-registry.json" "evidence/evidence-registry.json"]
   ["test-summary.json" "test-summary.json"]
   ;; Graph evidence artifacts (generated by graph/export.clj)
   ["graph-evidence.json" "evidence/graph-evidence.json"]
   ["evidence-graph.svg" "visualizations/evidence-graph.svg"]
   ["evidence-graph.json" "visualizations/evidence-graph.json"]])

(defn- resolve-run-dir
  "Resolve run directory from a user-provided argument.
   If it looks like a path (contains / or starts with .), use as-is.
   Otherwise, treat as run-id and look under results/runs/."
  [arg]
  (when-not arg
    (throw (ex-info "Missing run directory or run-id argument" {})))
  (let [f (io/file arg)]
    (if (or (.isAbsolute f) (.contains arg "/") (.startsWith arg "."))
      f
      (io/file "results" "runs" arg))))

(defn- read-commitment
  "Read pre-run-commitment.json from run-dir, returning keyword-keyed map or nil."
  [run-dir]
  (let [f (io/file run-dir "pre-run-commitment.json")]
    (when (.isFile f)
      (try (json/read-str (slurp f) :key-fn keyword) (catch Exception _ nil)))))

(defn- read-dag
  "Read execution-dag.json from run-dir, returning keyword-keyed map or nil."
  [run-dir]
  (let [f (io/file run-dir "execution-dag.json")]
    (when (.isFile f)
      (try (json/read-str (slurp f) :key-fn keyword) (catch Exception _ nil)))))

(defn pack!
  "Create an evidence pack from a run directory.

   Arguments:
     run-id-or-dir — run directory (e.g. results/runs/run-2026-01-01T00:00:00Z)
                     or just the run-id directory name.
     opts          — optional map with:
                     :pack/dir     — output directory (default: evidence-pack-<run-dir-name>)
                     :pack/tar     — if true, also create a .tar.gz (default: false)

   Returns {:pack/dir, :pack/manifest, :pack/root-hash, :pack/tar-path (if tar)}."
  [run-id-or-dir & [opts]]
  (let [opts (or opts {})
        run-dir (resolve-run-dir run-id-or-dir)
        _ (when-not (.isDirectory run-dir)
            (throw (ex-info (str "Run directory not found: " (.getAbsolutePath run-dir))
                            {:run-dir (str run-dir)})))
        run-id-str (.getName run-dir)
        out-dir (io/file (or (:pack/dir opts) (str "evidence-pack-" run-id-str)))
        manifest (atom [])]
    (.println *err* (str "Packing evidence from " run-dir " → " out-dir))
    (.mkdirs out-dir)

    ;; Copy manifest files (missing files are silently skipped)
    (doseq [[src-name tgt-name] pack-manifest-fields]
      (let [src (io/file run-dir src-name)
            tgt (io/file out-dir tgt-name)]
        (when (.exists src)
          (.mkdirs (.getParentFile tgt))
          (io/copy src tgt)
          (swap! manifest conj {:source src-name :target tgt-name
                                :size (.length src)
                                :sha256 (sha256-file (.getPath src))}))))

    ;; Read metadata for REPRODUCE.md
    (let [commitment (read-commitment run-dir)
          dag (read-dag run-dir)
          suite-key (or (:suite-key commitment) "<suite-key>")
          commit-hash (or (:commitment-hash commitment) "?")
          root-hash-dag (or (:root-hash dag) "?")
          node-count (or (:node-count dag) 0)
          scenario-paths (mapv (fn [n] (get-in n [:input-hashes :path])) (:nodes dag))]
      ;; Write REPRODUCE.md
      (spit (str out-dir "/REPRODUCE.md")
            (str "# Reproduce this evidence pack\n\n"
                 (format "Run: `%s`\n" run-id-str)
                 "Suite: `" suite-key "` (" node-count " scenarios)\n"
                 "Commitment: `" commit-hash "`\n"
                 "DAG root: `" root-hash-dag "`\n\n"
                 "## Prerequisites\n\n"
                 "1. Java 21+\n"
                 "2. `prf-runner-sew.jar` (from the release)\n"
                 "3. The scenario trace files below\n\n"
                 "## Scenario files\n\n"
                 (str/join "\n" (map (fn [p] (str "- `" p "`")) scenario-paths))
                 "\n\n"
                 "## Reproduce\n\n"
                 "```bash\n"
                 "java -jar prf-runner-sew.jar \\\n"
                 "  -m resolver-sim.minimal-runner \\\n"
                 "  --suite " suite-key " \\\n"
                 "  --fixtures ./fixtures\n"
                 "```\n"
                 (when commitment
                   (str "\n## Source\n\n"
                        "Tree hash: `" (get-in commitment [:source :tree-hash]) "`\n"
                        "Commit: `" (get-in commitment [:source :commit]) "`\n"
                        (when-let [dirty (get-in commitment [:source :dirty?])]
                          (str "Dirty: " dirty "\n")))))))

    ;; Compute pack root hash (SHA-256 of sorted manifest)
    (let [manifest-str (pr-str (sort-by :source @manifest))
          root-hash (let [d (MessageDigest/getInstance "SHA-256")]
                      (.update d (.getBytes manifest-str "UTF-8"))
                      (apply str (map #(format "%02x" (bit-and % 0xff)) (.digest d))))]
      ;; Write evidence-pack.json manifest
      (spit (str out-dir "/evidence-pack.json")
            (json/write-str {:pack/schema-version "evidence-pack.v1"
                             :pack/run-id run-id-str
                             :pack/generated-at (str (java.time.Instant/now))
                             :pack/manifest @manifest
                             :pack/root-hash root-hash}
                            {:indent true}))
      (.println *err* (str "  Root hash: " root-hash))

      ;; Optional tar.gz
      (let [tar-path (when (:pack/tar opts)
                       (let [tar-file (str (.getAbsolutePath out-dir) ".tar.gz")
                             abs-out-dir (.getAbsoluteFile out-dir)]
                         (try
                           (let [{:keys [exit err]} (shell/sh "tar" "czf" tar-file
                                                              "-C" (.getParent (.getAbsoluteFile out-dir))
                                                              (.getName abs-out-dir))]
                             (if (zero? exit)
                               (do (.println *err* (str "  Tar: " tar-file " (" (.length (java.io.File. tar-file)) " bytes)"))
                                   tar-file)
                               (do (.println *err* (str "  WARN: tar failed: " err)) nil)))
                           (catch Exception e
                             (.println *err* (str "  WARN: tar not available: " (.getMessage e))) nil))))]
        {:pack/dir (.getPath out-dir)
         :pack/manifest @manifest
         :pack/root-hash root-hash
         :pack/tar-path tar-path}))))

(defn verify
  "Verify an evidence pack: check all file hashes against the manifest.
   Returns {:valid? bool, :errors [str]}."
  [pack-dir]
  (let [pack-file (io/file pack-dir "evidence-pack.json")]
    (if-not (.exists pack-file)
      {:valid? false :errors [(str "evidence-pack.json not found in " pack-dir)]}
      (let [pack (json/read-str (slurp pack-file) :key-fn keyword)
            manifest (:pack/manifest pack [])
            errors (atom [])]
        (doseq [entry manifest]
          (let [tgt-path (str pack-dir "/" (:target entry))
                tgt-file (java.io.File. tgt-path)]
            (if-not (.exists tgt-file)
              (swap! errors conj (str "Missing file: " (:target entry)))
              (let [actual-size (.length tgt-file)
                    actual-sha256 (sha256-file tgt-path)]
                (when (not= (:size entry) actual-size)
                  (swap! errors conj (str "Size mismatch: " (:target entry)
                                          " expected " (:size entry) " got " actual-size)))
                (when (not= (:sha256 entry) actual-sha256)
                  (swap! errors conj (str "Hash mismatch: " (:target entry)
                                          " expected " (:sha256 entry) " got " actual-sha256)))))))
        (let [valid? (empty? @errors)]
          (println (str "Evidence pack " (if valid? "VERIFIED" "CORRUPT") ": " pack-dir))
          (doseq [e @errors] (println "  " e))
          {:valid? valid? :errors @errors})))))
